services:
  gaussianformer:
    build:
      context: .
      dockerfile: Dockerfile
    image: gaussianformer:latest
    container_name: gaussianformer
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix  # For GUI applications if needed
    environment:
      - DISPLAY=${DISPLAY:-:0}  # Use :0 as default if DISPLAY is not set
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute]
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    command: /bin/bash  # Interactive shell
    stdin_open: true
    tty: true
